apps/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('testeros.urls')),
]

testeros/urls.py
from django.conf.urls import url
from . import views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^$', views.home, name='home'),
    url(r'^.*/ajax/$', views.ajax_view, name='ajax'),
    url(r'^isocompare/$', views.isocompare, name='isocompare'),
    url(r'^packages/$', views.packages, name='packages'),
    url(r'^stapelip/$', views.stapelip, name='stapelip'),

    url(r'^stapelip/download/$', views.download, name='download'),
    url(r'^tests/download/$', views.download, name='download'),
    url(r'^testing/download/$', views.download, name='download'),

    url(r'^tests/$', views.tests, name='tests'),
    url(r'^scanner/$', views.scanner, name='scanner'),

    url(r'^testing/$', views.testing, name='testing'),
    url('^testing/test/(?P<journal_id>\d+)/$', views.testing_test, name='testing_test'),
    url(r'^repomanager/$', views.repomanager, name='repomanager'),
    url(r'^repoinfo/$', views.repoinfo, name='repoinfo'),
    url(r'^repolog/$', views.repolog, name='repolog'),

    url(r'^buildiso/$', views.buildiso, name='buildiso'),
    url(r'^buildisolog/$', views.buildisolog, name='buildisolog'),


    url(r'^settings/$', views.settings, name='settings'),
]

testeros/models.py
from django.db import models
from django.contrib.auth.models import User



class UserProfile(models.Model):
    username = models.CharField(max_length=150, blank=True, unique=True)
    note = models.TextField(blank=True)


class ObjectSf(models.Model):
    serial_num = models.IntegerField(unique=True)
    name = models.CharField(max_length=80)
    comment = models.TextField(blank=True, null=True)


class Tests(models.Model):
    object_sf_num = models.IntegerField()
    serial_num = models.IntegerField()
    name = models.CharField(max_length=60, blank=True, null=True)
    prerequisites = models.TextField(blank=True, null=True)
    expected_result = models.TextField(blank=True, null=True)
    test_procedure = models.TextField(blank=True, null=True)
    test_result = models.TextField(blank=True, null=True)
    file1 = models.CharField(max_length=250, blank=True, null=True)
    file2 = models.CharField(max_length=250, blank=True, null=True)


class Testing(models.Model):
    begin_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    os_name = models.CharField(max_length=20, blank=True, null=True)
    os_version = models.CharField(max_length=20, blank=True, null=True)
    os_release = models.CharField(max_length=20, blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    status = models.IntegerField()


class TestJournal(models.Model):
    testing_id = models.IntegerField()
    test_id = models.IntegerField(blank=True, null=True)
    begin_date = models.DateTimeField(blank=True, null=True)
    end_date = models.DateTimeField(blank=True, null=True)
    comment = models.TextField(blank=True, null=True)
    status = models.IntegerField()


class Settings(models.Model):
    path_to_gl_iso = models.CharField(max_length=250, blank=True, null=True)
    path_to_ro_iso = models.CharField(max_length=250, blank=True, null=True)
    stapel = models.TextField(blank=True, null=True)
    repo = models.TextField(blank=True, null=True)


class ActionLog(models.Model):
    user_name = models.CharField(max_length=25, blank=True, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    status = models.IntegerField(null=True)
    message = models.CharField(max_length=250, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    stapel = models.CharField(max_length=25, blank=True, null=True)
    repo = models.CharField(max_length=25, blank=True, null=True)
    tag = models.CharField(max_length=25, blank=True, null=True)
    packages = models.TextField(blank=True, null=True)
    replace = models.BooleanField(default=False)
    entire = models.BooleanField(default=False)
    update = models.BooleanField(default=False)
    sign = models.BooleanField(default=False)

class BuildIsoSettings(models.Model):
    name = models.CharField(max_length=25, blank=True, null=True)
    comment = models.TextField(max_length=250, null=True)
    created_at = models.DateTimeField(blank=True, null=True)
    dir = models.CharField(max_length=250, blank=True, null=True)
    label = models.CharField(max_length=25, blank=True, null=True)
    rel_name = models.CharField(max_length=25, blank=True, null=True)
    rel_short_name = models.CharField(max_length=25, blank=True, null=True)
    rel_ver = models.CharField(max_length=25, blank=True, null=True)
    comps_file_path = models.CharField(max_length=250, blank=True, null=True)
    var_file_path = models.CharField(max_length=250, blank=True, null=True)
    pkgset_repos = models.TextField(blank=True, null=True)

class BuildIso_Log(models.Model):
    process_id = models.IntegerField(null=True)
    user_id = models.IntegerField(null=True)
    inform = models.CharField(max_length=250, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    close_at = models.DateTimeField(null=True)
    status = models.IntegerField(null=True)

testeros/forms.py
from django import forms

from .models import Testing

class PassingTestCaseForm(forms.ModelForm):

    class Meta:
        model = Testing
        fields = ('os_name', 'os_version', 'os_release')

testeros/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse, Http404
from django.utils import timezone

from .models import ObjectSf, Tests, Testing, TestJournal, Settings, ActionLog, UserProfile, BuildIsoSettings
from .models import BuildIso_Log

from .forms import PassingTestCaseForm

import ntpath, datetime, json, sys, os
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import ssl
from magic.buildiso import executeBuildIso

import datetime


# -----------
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
import dateutil.parser as dp
from django.http import JsonResponse



from magic.isocompare2 import compareIso, searchPkgOnIso, getIsoLst
import magic.kojirepo as repo
from magic.parsetest import parseTestFile
from magic.vulnersscanner import runScanner


def ajax_view(request):
    try:
        if request.method == 'POST':
            action = request.POST.get('action')

            # сравнение iso образов
            if action == 'compareIso':
                return render_to_response('testeros/isocompare/ajax_result.html', {
                    'result': compareIso(iso1_path=request.POST.get('iso1'), iso2_path=request.POST.get('iso2'))
                })


            # поиск пакетов на iso образе
            if action == 'searchPkg':
                return render_to_response('testeros/packages/ajax_result.html', {
                    'result': searchPkgOnIso(iso_path=request.POST.get('iso'), pkg_mask=request.POST.get('mask')),
                })

            # ********************************STAPEL IP***********************************
            # ****************************************************************************
            # получение списка пакетов со стапеля
            if action == 'getPkgLst':
                return HttpResponse(json.dumps(repo.getPkgLst(request.POST.get('stapelUrl'))),
                                    content_type='application/json')

            # список сборок для пакета
            if action == 'getBuildLst':
                return HttpResponse(json.dumps(repo.getBuildLst(stapelUrl=request.POST.get('stapelUrl'),
                                                                pkgId=request.POST.get('pkgId'))),
                                    content_type='application/json')

            # генерация файла для установки пакета
            if action == 'genRepoFile':
                import os
                file_path = os.path.join('/home/yarikov/upload', repo.generateFileinst(
                    dir='/home/yarikov/upload', stapel_url=request.POST.get('url'),
                    build_id=request.POST.get('build_id')))
                return HttpResponse(file_path, content_type='text/html')


            # ********************************TESTCASE************************************
            # ****************************************************************************
            # получаем информацио тесте
            if action == 'getTestInfo':
                import os
                testInfo = parseTestFile(os.path.join(os.getcwd(), request.POST.get('testFile1')))
                return render_to_response('testeros/tests/ajax-testinfo.html', {'result': testInfo,
                                                                                'testFile2': request.POST.get('testFile2')})

            # скачиваем файл теста
            if action == 'getTestFile':
                file_path = '/home/yarikov/web/testeros/apps/' + request.POST.get('testFile')
                return HttpResponse(file_path, content_type='text/html')



            # получаем информацию о тестировании
            if action == 'getTestingInfo':
                objectSf = ObjectSf.objects.all()
                tests = Tests.objects.all()
                objectSf_list = list(objectSf)
                tests_list = list(tests)

                result = []

                for osf in objectSf_list:
                    tests = []
                    for test in tests_list:
                        if test.object_sf_num == osf.serial_num:
                            tests.append(dict(id=test.id, num=test.serial_num, name=test.name, file1=test.file1,
                                              file2=test.file2))

                    result.append(dict(num=osf.serial_num, name=osf.name, tests=tests))

                testingId = request.POST.get('id', '')

                for i in result:
                    for k in i['tests']:
                        testInfo = TestJournal.objects.filter(testing_id=testingId, test_id=k['id']).values()
                        if testInfo:
                            k.update(begin_date=testInfo[0]['begin_date'], end_date=testInfo[0]['end_date'],
                                     comment=testInfo[0]['comment'], status=testInfo[0]['status'],
                                     journal_id=testInfo[0]['id'])
                            # print(testInfo[0]['begin_date'])
                        else:
                            # если не найдено теста в журнале
                            pass

                # for i in result:
                #     print(i)


                result = sorted(result, key=lambda x: x['num'])

                for res in result:
                    res['tests'] = sorted(res['tests'], key=lambda x: x['num'])



                # id = request.POST.get('id', '')
                # testingInfo = TestJournal.objects.filter(testing_id=id)


                return render_to_response('testeros/testing/ajax-journal.html', {'result': result})
                # data = serializers.serialize('json', testingInfo)
                # return HttpResponse(data, content_type='application/json')

            # смена статуса у теста
            if action == 'editTestStatus':
                journalId = request.POST.get('testId')
                status = request.POST.get('status')
                status = int(status)

                now = datetime.datetime.now(tz=timezone.utc)
                if status == 4 or status == 3 or status == 2:
                    TestJournal.objects.filter(id=journalId).update(end_date=now, status=status)
                elif status == 1:
                    TestJournal.objects.filter(id=journalId).update(begin_date=now, end_date=None, status=1)

                # проверка на состояние тестов в журнале для статуса тестирования
                testJournal = TestJournal.objects.filter(id=journalId).values()
                testJournals = TestJournal.objects.filter(testing_id=testJournal[0]['testing_id']).values()

                status0 = 0
                status1 = 0
                status2 = 0
                status3 = 0
                status4 = 0
                for i in testJournals:
                    if i['status'] == 0:
                        status0 += 1
                    if i['status'] == 1:
                        status1 += 1
                    if i['status'] == 2:
                        status2 += 1
                    if i['status'] == 3:
                        status3 += 1
                    if i['status'] == 4:
                        status4 += 1

                if status0 == 0 and status1 == 0 and status3 == 0:
                    # print('set status пройден')
                    Testing.objects.filter(id=testJournal[0]['testing_id']).update(status=3)
                elif status0 == 0 and status1 == 0:
                    Testing.objects.filter(id=testJournal[0]['testing_id']).update(status=2)
                else:
                    Testing.objects.filter(id=testJournal[0]['testing_id']).update(status=0)


                return HttpResponse('ok', content_type='text/html')

            # сохранение комментария
            if action == 'saveComment':
                journalId = request.POST.get('testId')
                text = request.POST.get('text')

                if TestJournal.objects.filter(id=journalId).update(comment=text) == 1:
                    return HttpResponse('ok', content_type='text/html')
                else:
                    raise Exception('Не удалось сохранить комментарий.')



            # ********************************REPO****************************************
            # ********************************REPO MANAGER********************************
            # ****************************************************************************
            # получить список тегов со стапеля
            if action == 'getTagList':
                try:
                    data = repo.get_tag_list(request.POST.get('stapel_url', ''))
                    jsond = json.dumps(data)
                    return HttpResponse(jsond, content_type='application/json')
                except:
                    raise Exception('Невозможно загрузить список тегов.')

            # получить список пакетов со стапеля по тегу
            if action == 'getPkgsByTag':
                data = repo.get_pkgs_by_tag(request.POST.get('stapel_url'), request.POST.get('tag_id'))
                jsond = json.dumps(data)
                return HttpResponse(jsond, content_type='application/json')

            # получить список сборок со стапеля для пакета по тегу
            if action == 'getBuildsByTag':
                data = repo.get_builds_by_tag(request.POST.get('stapel_url'), request.POST.get('pkg_id'),
                                              request.POST.get('tag_id'))
                jsond = json.dumps(data)
                return HttpResponse(jsond, content_type='application/json')

            # экспорт пакетов
            if action == 'exportRPMS':
                now = datetime.datetime.now(tz=timezone.utc)
                stapel = request.POST.get('stapel_url')
                repoUrl = request.POST.get('repo')

templates/testeros/testing/ajax-journal.html
{#ajax begin#}

<div class="row" id="result-content">
    <div class="col">

        <h4 class="title">Тестирование ...</h4>

        <table class="table" id="table-testing-tests">
            <thead class="blue-grey lighten-4">
            <tr>
                {#        <th style="width:10px"></th>#}
                <th style="width:350px">Имя</th>
                <th style="width:160px">Дата начала</th>
                <th style="width:160px">Дата завершения</th>
                <th>Комментарий</th>
                <th class="text-center" style="width:100px">Статус</th>
                <th style="width:50px;"></th>
                <th style="width:50px;"></th>
            </tr>
            </thead>

            <tbody id="table-testing-test-data">
            {% if result %}
                {% for elem in result %}

                    <tr class="">
                        <td colspan="6"><b>Тестирование ФБО «{{ elem.name }}»</b></td>
                    </tr>

                    {% for test in elem.tests %}

                        <tr class="table-testing-test-row" journalid="{{ test.journal_id }}">

                            <td class="test-td">{{ test.num }}. {{ test.name }}</td>

                            {% if test.begin_date %}
                                <td class="test-td">{{ test.begin_date|date:'d E Y, H:i' }}</td>
                            {% else %}
                                <td class="test-td">-</td>
                            {% endif %}

                            {% if test.end_date %}
                                <td class="test-td">{{ test.end_date|date:'d E Y, H:i' }}</td>
                            {% else %}
                                <td class="test-td">-</td>
                            {% endif %}

                            {% if test.comment %}
                                <td class="test-td">{{ test.comment }}</td>
                            {% else %}
                                <td class="test-td">-</td>
                            {% endif %}


                            <td class="test-td text-center" style="padding-top: 16px;">
                                {% if test.status == 0 %}
                                    -
                                {% endif %}

                                {% if test.status == 1 %}
                                    <i class="fas fa-hourglass-start color-info"></i>
                                {% endif %}

                                {% if test.status == 2 %}
                                    <i class="fas fa-times color-warning"></i>
                                {% endif %}

                                {% if test.status == 3 %}
                                    <i class="fas fa-minus color-danger"></i>
                                {% endif %}

                                {% if test.status == 4 %}
                                    <i class="fas fa-check color-success"></i>
                                {% endif %}
                            </td>

                            <td class="text-center">
                                {% if test.file2 %}
                                    <h5><a id="upload" testFile2="{{ test.file2 }}" style="margin: 0 10px"><i class="fas fa-download"></i></a></h5>
                                {% endif %}
                            </td>

                            <td class="text-center">
                                {% if test.file1 %}
                                    <h5><a id='url' test_url='test/{{ test.journal_id }}' style="margin: 0 10px"><i class='fas fa-eye'></i></a></h5>
                                {% endif %}
                            </td>




                        </tr>

                    {% endfor %}

                {% endfor %}
            {% endif %}
            </tbody>
        </table>

    </div>
</div>

<div class="row float-right" style="padding-top: 40px">
    <div class="col">
        <a id="a-scrollto">Вверх <i class="fas fa-arrow-up"></i></a> |
        <a onClick="javascript:CallPrint('result-content');">Печать <i class="fas fa-print"></i></a>
    </div>
</div>
{#ajax end#}

templates/testeros/testing/modalform.html
<div class="modal fade" id="testingNewModal" tabindex="-1" role="dialog" aria-labelledby="testingNewModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="testingNewModalLabel">Новое тестирование</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <form method="POST" class="passing-test-case-form">{% csrf_token %}
                <div class="modal-body">

                    <label class="grey-text font-weight-light">Cистема</label>
                    <select class="form-control" name="os_name" id="id_os_name">
                        <option value="ГосЛинукс">ГосЛинукс</option>
                        <option value="РедОС">РедОС</option>
                    </select>

                    <br>

                    <label class="grey-text font-weight-light">Версия</label>
                    <input class="form-control" name="os_version" maxlength="20" id="id_os_version" type="text">

                    <br>

                    <label class="grey-text font-weight-light">Релиз</label>
                    <input class="form-control" name="os_release" maxlength="20" id="id_os_release" type="text">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-outline-danger waves-effect" data-dismiss="modal">Отмена</button>
                    <button type="submit" class="save btn btn-danger">Создать</button>
                </div>
            </form>
        </div>
    </div>
</div>

templates/testeros/testing/start.html
{% extends "base.html" %}

{% block css2 %}
    <style type="text/css">

        .table-testing-row:hover {
            cursor: pointer;
            background:#e1ebf0;
        }

        a .fas:hover {
            color: #9bb4e2;
        }

        .table-testing-test-row:hover {
            background: #cfd8dc4d;
        }

        .title-test {
            display: none;
            line-height: 0;
            cursor: pointer;
        }

        .title-result {
            font-size: 21px;
            font-weight: 800;
            margin-bottom: 10px;
            color: #314d7c;
            padding-top: 25px;
            padding-bottom: 5px;
            border-bottom-color: #c3cad5;
            border-bottom-style: solid;
            border-bottom-width: 1px;
        }

        .code {
            padding: 1em;
            border: 1px dashed #2f6fab;
            color: #000;
            background-color: #f9f9f9;
            border-radius: 4px;
            line-height: 1.1em;
            font-family: Courier New, Courier, mono;
            font-size: 12px;
            font-style: italic;
            margin-bottom: 10px;
            margin-top: 10px;
        }

        table.table td.test-td {
            padding-top: 0.6rem;
            padding-bottom: 0.6rem;
        }
    </style>
{% endblock %}

{% block content %}

    <!--title-->
    <div class="row" id="start" style="padding-bottom: 20px;">
        <div class="col-xs-12 col-md-12 col-lg-12">
            <p style="text-align: justify;"><span class="header">Testing</span> - журнал тестирвоания
                <a data-container="body" data-toggle="popover" data-placement="right"
                   data-content="Помощь."><i class="fa fa-question-circle"> </i></a>
            </p>
        </div>
    </div>

    <!--form-->
    <div class="row">
        <div class="col-xs-12 col-md-12 col-lg-12">
            <div class="card">
                <div class="card-body">

                    {#header#}
                    {#                    <div class="row">#}
                    {#                        <div class="col">#}
                    {#                            <h3 class="title">Журнал тестирования</h3>#}
                    {#                        </div>#}
                    {#                        <div class="col" style="padding-top: 7px;">#}
                    {#                            <a class="float-right btn btn-primary btn-sm" href="{% url 'tests' %}"><i class="far fa-list-alt"></i> Список тестов</a>#}
                    {#                            <a class="float-right btn btn-success btn-sm" data-toggle="modal" data-target="#testingNewModal"><i class="fas fa-plus"></i> Создать </a>#}
                    {#                        </div>#}
                    {#                    </div>#}

                    {#testing table#}
                    <div class="row">
                        <div class="col">

                            <table class="table table-select" id="table-testing">
                                <thead class="blue-grey lighten-4">
                                <tr>
                                    <th >Имя</th>
                                    <th >Версия</th>
                                    <th >Релиз</th>
                                    <th style="width:200px">Дата начала</th>
                                    <th style="width:200px">Дата завершения</th>
                                    <th class="text-center" style="width:100px">Статус</th>
                                </tr>
                                </thead>

                                <tbody id="table-testing-data">
                                {% if testing %}
                                    {% for elem in testing %}
                                        <tr class="table-testing-row" num="{{ elem.id }}">
                                            <td><b>{{ elem.os_name }}</b></td>
                                            <td><b>{{ elem.os_version }}</b></td>
                                            <td><b>{{ elem.os_release }}</b></td>
                                            <td><b>{{ elem.begin_date|date:'d E Y, H:i' }}</b></td>
                                            <td><b>{{ elem.end_date }}</b></td>

                                            {% if elem.status == 0 %}
                                                <td class="text-center"><i class="fas fa-hourglass-start color-info"></i></td>
                                            {% endif %}

                                            {% if elem.status == 1 %}
                                                <td class="text-center"><i class="fas fa-times color-warning"></i></td>
                                            {% endif %}

                                            {% if elem.status == 2 %}
                                                <td class="text-center"><i class="fas fa-minus color-danger"></i></td>
                                            {% endif %}

                                            {% if elem.status == 3 %}
                                                <td class="text-center"><i class="fas fa-check color-success"></i></td>
                                            {% endif %}
                                        </tr>
                                    {% endfor %}
                                {% endif %}
                                </tbody>
                            </table>
                        </div>
                    </div>

                    {#testing test-journal#}
                    <div class="row" style="padding-top: 30px">
                        <div class="col parent" id="test-journal">
                            {#ajax testjournal#}
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    {% include "testeros/testing/modalform.html" %}

{% endblock %}


{% block js %}
    <script type="text/javascript">

        {#выделение строки таблицы при нажатии#}
        $('.table-testing-row').on('click', function () {
            $('#table-testing-data .table-testing-row').css('background', 'none');
            $(this).css('background', '#e1ebf0');
        });



        {#ссылка на тест#}
        {#$('.parent').on('click', '.line-table-test', function () {#}
        {#var journalId = $(this).attr('journalid');#}
        {#window.location.href = "test/" + journalId;#}
        {#});#}
        $("body").on('click','a[id="url"]',function(){
            window.open($(this).attr('test_url'));
        });



        {#загруза test-journal#}
        $('.table-testing-row').click(function() {
            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
            var num = $(this).attr('num');
            $.ajax({
                type: "POST",
                url: "ajax/",
                data: {
                    action: 'getTestingInfo',
                    id: num,
                },
                cache: false,

                success: function (data) {
                    {#console.log(data);#}
                    $("#test-journal").append(data);
                },

                error: function (request, error) {
                    // console.log(error + request.status + request.statusText);
                    $.alert("Ошибка ", {type: 'danger'}, request.status + request.responseText);
                },

                beforeSend: function(xhr, settings) {
                    $("#test-journal").empty();
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },

                complete: function() {
                },
            });
        });


        {#скачиваем файл теста#}
        $("body").on('click','a[id="upload"]',function(){
            var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
            var testFile2 = $(this).attr('testFile2');

            $.ajax({
                type: "POST",
                url: "ajax/",
                data: {
                    action: 'getTestFile',
                    testFile: testFile2,
                },
                cache: false,

                success: function (data) {
                    {#console.log('load' + data);#}
                    window.location.href = "download/?filepath=" + data;
                },

                error: function (request, error) {
                    {#console.log(error + request.status + request.statusText);#}
                    $.alert("При загрузке файла.", {type: 'danger'}, request.status + request.responseText);
                },

                beforeSend: function(xhr, settings) {
                    $('.loader-block-1').css("display", "block");

                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader("X-CSRFToken", csrftoken);
                    }
                },

                complete: function() {
                    $('.loader-block-1').css("display", "none");
                },
            });
        });



        {#очистка modal-form и установка фокуса#}
        $('#testingNewModal').on('show.bs.modal', function () {
            $(this).find('form').trigger('reset');
        });
        $('#testingNewModal').on('shown.bs.modal', function () {
            document.getElementById("id_os_name").focus();
        });



    </script>
{% endblock %}